### ISSUE TITLE
CAD export doesn't find the script and Schema of Activity

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/gui#10]
When exporting from the Composite Activity Description, the Export tools doesn't seems to find Script and Schema when the are referenced by a "relative path" in the Activity.
=> The export tools doesn't create the files related.

Note that it's working fine if I try exporting Script and Schema "manually".
Do you think it mights be related to the changes you made to allow referencing with relative path ?

error message I got from the GUI (same for the Script):
![bug_export_1](https://cloud.githubusercontent.com/assets/9263650/10132039/a1c5d628-65d4-11e5-9fbd-50f355066923.png)

Here my activity definition :
![bug_export_3](https://cloud.githubusercontent.com/assets/9263650/10132067/dd9291b4-65d4-11e5-9319-406fb9eb9488.JPG)

And here the log (same for the Script):

```
EXCEPTION:java.io.FileNotFoundException: E:\Sauvegarde\Module_agilium-desgin\Vtest\OD\agilium\company\AglCompanyDetails.xsd (Le chemin d’accès spécifié est introuvable)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at java.io.FileWriter.<init>(FileWriter.java:90)
    at org.cristalise.kernel.utils.FileStringUtility.string2File(FileStringUtility.java:120)
    at org.cristalise.gui.lifecycle.desc.ElemActDefOutcomeHandler.exportSchema(ElemActDefOutcomeHandler.java:238)
    at org.cristalise.gui.lifecycle.desc.ElemActDefOutcomeHandler.exportAct(ElemActDefOutcomeHandler.java:148)
    at org.cristalise.gui.lifecycle.desc.ElemActDefOutcomeHandler.exportAct(ElemActDefOutcomeHandler.java:167)
    at org.cristalise.gui.lifecycle.desc.CompActDefOutcomeHandler.export(CompActDefOutcomeHandler.java:259)
    at org.cristalise.gui.tabs.ViewpointPane.saveOutcomeToFile(ViewpointPane.java:360)
    at org.cristalise.gui.tabs.ViewpointPane.actionPerformed(ViewpointPane.java:344)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by abranson** [comment]
Yes, I should probably update that :)

**Comment by smassonnat** [comment]
It would be really usefull and will save me a LOT of time ;)

**Comment by kovax** [comment]
Relative path is not supported, use Dependency instead. The simple name should also work.
