### ISSUE TITLE
Outcome not visible in Data Viewer for Agent

### ISSUE THREAD

**Issue by smassonnat** [cristal-ise/gui#12]
I'm not able to see the outcome of my Activity in the "Data Viewer" tab of an Agent. But I saw there should be one from the "History" pane.  Is it normal ?

![bug_gui_data_viewer_agent_2](https://cloud.githubusercontent.com/assets/9263650/10242926/d27c5d28-68f4-11e5-95ed-f877f268bad5.JPG)

![bug_gui_data_viewer_agent](https://cloud.githubusercontent.com/assets/9263650/10242925/d15480ec-68f4-11e5-977c-9c32a007f02d.JPG)

Moreover, if I execute another activity, the outcome seems to appear in the list of Outcome
![bug_gui_data_viewer_agent_3](https://cloud.githubusercontent.com/assets/9263650/10243161/04ee2046-68f7-11e5-8e80-d58d3876e6a6.JPG)

But can never be seen (i got this error in GUI log when I select the outcome)

```
EXCEPTION:org.cristalise.kernel.common.PersistencyException: IDL:org.cristalise.kernel/common/PersistencyException:1.0  Outcome() - Outcome version was an invalid number: user
    at org.cristalise.kernel.persistency.outcome.Outcome.<init>(Outcome.java:123)
    at org.cristalise.kernel.persistency.outcome.Outcome.<init>(Outcome.java:103)
    at org.cristalise.storage.ProxyLoader.get(ProxyLoader.java:85)
    at org.cristalise.kernel.persistency.ClusterStorageManager.get(ClusterStorageManager.java:252)
    at org.cristalise.kernel.persistency.TransactionManager.get(TransactionManager.java:100)
    at org.cristalise.kernel.entity.proxy.ItemProxy.getObject(ItemProxy.java:335)
    at org.cristalise.kernel.entity.proxy.MemberSubscription.update(MemberSubscription.java:117)
    at org.cristalise.kernel.entity.proxy.ItemProxy.notify(ItemProxy.java:426)
    at org.cristalise.kernel.entity.proxy.ProxyManager.processMessage(ProxyManager.java:123)
    at org.cristalise.kernel.entity.proxy.ProxyServerConnection.run(ProxyServerConnection.java:77)

ERROR  : Member Subscription: could not load Outcome//agilium/user/AglUserDetails/0/13
EXCEPTION:org.cristalise.kernel.common.ObjectNotFoundException: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0  ClusterStorageManager.get() - Path Outcome//agilium/user/AglUserDetails/0/13 not found in /entity/e3a692b3-9af7-4f4d-898f-dd19e1337c3e
    at org.cristalise.kernel.persistency.ClusterStorageManager.get(ClusterStorageManager.java:263)
    at org.cristalise.kernel.persistency.TransactionManager.get(TransactionManager.java:100)
    at org.cristalise.kernel.entity.proxy.ItemProxy.getObject(ItemProxy.java:335)
    at org.cristalise.kernel.entity.proxy.MemberSubscription.update(MemberSubscription.java:117)
    at org.cristalise.kernel.entity.proxy.ItemProxy.notify(ItemProxy.java:426)
    at org.cristalise.kernel.entity.proxy.ProxyManager.processMessage(ProxyManager.java:123)
    at org.cristalise.kernel.entity.proxy.ProxyServerConnection.run(ProxyServerConnection.java:77)

```

And if I refresh the "DataViewer" pane, it disapear.

**Comment by abranson** [comment]
Oh gosh that schema name path is going to be a bigger problem that we thought...

**Comment by smassonnat** [comment]
I agree. 
Do you think it'll be too costly to correct all the impacts (see #10) ?

I'd like to use the subcontext inside a module but if it's not fully operational, it mights be better to go back for now and make it a proper feature of a futur version.
What do you think ?

**Comment by abranson** [comment]
Need to think about it, but given that the benefit is quite small it may be better to roll it back for the time being. With the previous mechanism you can still use categories, but referencing resources must be by name only.

**Comment by smassonnat** [comment]
Ok, I think I will do that.
Will the collection stuff (cristal-ise/kernel#4) help to solve that later on ?

**Comment by abranson** [comment]
Yeah, but we'll have to identify every point in the kernel where the resource is referenced, which includes the Event.schemaName field and the Outcome and Viewpoint storage paths, in this case.

**Comment by abranson** [comment]
The changes causing this have been rolled back
