### ISSUE TITLE
Cristalise Gui does not generate an ordered XML elements for <xs:sequence> schema elements

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/gui#18]
When we have a schema containing <xs:sequence> element, the child elements should be provided in order. However, Cristalise Gui create a new XML file in a wrong order.

Here is a schema example:
`````
<xs:element name="AglDbAlias_Details">
        <xs:complexType>
            <xs:sequence>
		<xs:element minOccurs="0" maxOccurs="1" name="label" type="xs:string"/>
                <xs:element minOccurs="0" maxOccurs="1" name="comment" type="xs:string"/>                
                <xs:element name="properties">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="0" name="property" type="property"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
`````

Cristalise Gui generate the following XML file (which is wrong):

``````
<AglDbAlias_Details>
  <properties>
    <property name="v2">p2</property>
    <property name="v1">p1</property>
  </properties>
  <label>MySQL</label>
  <comment>MySQL Connector</comment>
</AglDbAlias_Details>
``````

`properties` should be the last element.

I have the following exception validator exception:

``````
2016-04-21 10:18:19.436 (1377.704s) - EXCEPTION:org.cristalise.kernel.common.InvalidDataException: IDL:org.cristalise.kernel/common/InvalidDataException:1.0  ERROR: cvc-complex-type.2.4.d: Invalid content was found starting with element 'label'. No child element is expected at this point.

	at org.cristalise.kernel.entity.proxy.AgentProxy.execute(AgentProxy.java:142)
	at org.cristalise.gui.tabs.execution.DefaultExecutor.execute(DefaultExecutor.java:48)
	at org.cristalise.gui.tabs.execution.ActivityViewer.run(ActivityViewer.java:335)
	at java.lang.Thread.run(Thread.java:745)
``````

**Comment by abranson** [comment]
This is a very long standing bug from the very first version of the outcome form. It would be a bit of a pain to fix as it would make the insertion code much more complicated than it is currently. It's always been low priority though, as XML structures like this are quite difficult to manage and parse. I'd suggest as a workaround either moving the comment field to the end, setting it minOccurs=1, or wrapping it in its own element.

**Comment by kovax** [comment]
This will also happen for schema like this, the optional elements are added after the none optional ones:

```xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TransactionDetails">
    <xs:annotation>
      <xs:documentation>Details of a new transaction</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence minOccurs="0" >
        <xs:element maxOccurs="1" minOccurs="1" name="Direction" />
        <xs:element maxOccurs="1" minOccurs="1" name="TransactionType" />
        <xs:element maxOccurs="1" minOccurs="0" name="DocketNo" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="0" name="ContractRefNo" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="0" name="HaulerDocumentNo" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="0" name="HaulerName" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="1" name="TruckPlateNo" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="0" name="TrailerPlateNo" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="1" name="DriverName" type="xs:string"/>
        <xs:element maxOccurs="1" minOccurs="1" name="LoadingLocation" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```
The GUI will generate an XML like this:

```xml
<TransactionDetails>
	<Direction>Intake</Direction>
	<TransactionType>PickupBulk</TransactionType>
	<TruckPlateNo>abc123</TruckPlateNo>
	<DriverName>tata</DriverName>
	<LoadingLocation>Bin1</LoadingLocation>
	<DocketNo>111111</DocketNo>
	<ContractRefNo>22222</ContractRefNo>
	<HaulerDocumentNo>333333</HaulerDocumentNo>
	<HaulerName>KZ</HaulerName>
</TransactionDetails>
```
